#!/bin/bash
# argument ist die ID oder -name statt -id, dann kann der window name angegeben werden
# mit $(xdotool getactivewindow) bekommt man das gerade aktive fenster
{ read __ WIDTH; read __ HEIGHT; read __ __ BORDER_WIDTH; } < <(xwininfo -id $(xdotool getactivewindow) | grep -o -e 'Height:.*' -e 'Width:.*' -e 'Border width:.*')

feh -Z -N -Y -z -B black -geometry=${WIDTH}x${HEIGHT} -p -R 60 -. $@
